// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
// Next.js convention: .env.local takes precedence over .env. Load both so
// `prisma migrate dev` / `prisma db push` see the same DATABASE_URL the app does.
loadEnv({ path: ".env.local", override: true });
loadEnv();
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
